export const createPost = async (apiBaseUrl, payload) => {
  let response;

  try {
    response = await fetch(`${apiBaseUrl}/api/posts/create`, {
      method: 'POST',
      credentials: 'include',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(payload),
    });
  } catch (error) {
    console.error('Error sending the post to the backend:', error);
    throw new Error('A network error occurred while sending the post.');
  }

  const responseText = await response.text();
  let data = null;

  try {
    data = responseText ? JSON.parse(responseText) : null;
  } catch (parseError) {
    console.error("Couldn't parse backend response:", parseError);
  }

  console.log('Backend response when creating post:', data);
  console.log('Post generated by Gemini from backend:', data?.post?.content);

  if (!response.ok) {
    throw new Error(data?.error ?? 'The backend returned an unexpected error.');
  }

  return data?.post ?? null;
};

export const publishPost = async (apiBaseUrl, { platform, platformLabel, post }) => {
  const endpoint = platform === 'instagram' ? '/api/posts/publish/instagram' : '/api/posts/publish';
  let response;

  try {
    response = await fetch(`${apiBaseUrl}${endpoint}`, {
      method: 'POST',
      credentials: 'include',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ post }),
    });
  } catch (error) {
    console.error(`Error publishing the post to ${platformLabel}:`, error);
    throw new Error(`A network error occurred while publishing to ${platformLabel}.`);
  }

  const data = await response.json();

  console.log(`Backend response when publishing to ${platformLabel}:`, data);

  if (!response.ok) {
    throw new Error(data?.error ?? `We couldn't publish the post to ${platformLabel}.`);
  }

  return data;
};
